# --- POAM training with IQL uncontrolled agents only on 3s_vs_5z ---

# --- pymarl options ---
runner: "parallel"
mac: "open_train_mac"
env: "sc2"
non_overridable: ['mac']
env_args:
  map_name: "3s_vs_5z"
batch_size_run: 8
test_nepisode: 128
test_interval: 50000
test_greedy: True

log_interval: 50000
runner_log_interval: 50000
learner_log_interval: 50000
t_max: 20000050
use_cuda: True
buffer_cpu_only: True
log_discounted_return: False

# ---  Logging/eval options ---
use_tensorboard: True
save_model: True
save_model_interval: 2000000
checkpoint_path: ""
render: False

# --- Default learning hyperparameters ---
gamma: 0.99
batch_size: 32
buffer_size: 32
lr: 0.0005
optim_alpha: 0.99
optim_eps: 0.00001
grad_norm_clip: 10
add_value_last_step: True

# --- Default agent parameters ---
agent: "rnn"
use_rnn: True
hidden_dim: 64
obs_last_action: True

# --- Open train Parameters ---
test_verbose: False
save_replay: False
eval_mode: null
local_results_path: 3sv5z/open_train/poam-vs-iql

# --- agents to load ---
n_uncontrolled: null
trained_agents:
  agent_0:
    agent_loader: rnn_train_agent_loader
    agent_path: ""
uncntrl_agents:
  agent_iql:
    agent_loader: rnn_eval_agent_loader
    agent_path: 3sv5z/iql/models/iql_baseline_seed=1285842_02-29-22-50-45
    load_step: best
    n_agents_to_populate: 2
    test_mode: True

# --- Experiment running params ---
repeat_id: 1
label: baseline
hypergroup: null
